name: Despliegue a QA

on:
    pull_request:
        branches:
            - qa
        types: [closed]

jobs:
    greet:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            - name: Send greeting
              run: echo "Hello World QA"